export const regalConfig = {
  id: "regal",
  name: "Regal Portal",
  selectors: {
    username: "input[name='identifier'][autocomplete='username']",
    usernameSubmit: "input[type='submit'][value='Next']",
    password: "input[name='credentials.passcode'][type='password']",
    passwordSubmit: "input[type='submit'][value='Verify']",
    errorContainer: "[data-se='o-form-error-container']",
    dashboardHeading: "h2:has-text('Dashboard')",
    dashboardText: "text=Dashboard",
    myAppsHeading: "h2:has-text('My Apps')",
    myAppsText: "text=My Apps",
    signOut: "a[data-se='topbar--sign-out'][href='/login/signout']",
    userMenu: "button:has-text('Regal Medical Group'), [aria-label*='account menu' i], [data-se*='user' i]",
    regalExpressAccessApp: "a[data-se='app-card'][aria-label='launch app Regal Express Access (REA)'], a[data-se='app-card']:has-text('Regal Express Access'), a:has-text('Regal Express Access')",
    switchAuthenticator: "a[data-se='switchAuthenticator']",
    emailAuthenticatorSelect: "[data-se='okta_email'] a[data-se='button'], a[aria-label*='Select Email' i]",
    emailSendSubmit: "input[type='submit'][value='Send me an email']",
    emailEnterCodeInstead: "button.enter-auth-code-instead-link:has-text('Enter a verification code instead')",
    googleAuthenticatorSelect: "[data-se='google_otp'] a[data-se='button'], a[aria-label='Select Google Authenticator.']",
    googleAuthenticatorCode: "input[name='credentials.passcode'][type='text']",
    googleAuthenticatorSubmit: "input[type='submit'][value='Verify']",
    siteSelect: "select[id$='_header_ddlSite'], select[name$='$header$ddlSite']",
    viewClaimsLink: "a:has-text('View Claims'), a[href*='selclaimmember.asp'], a[href*=\"navigateFromSideMenuTo('selclaimmember.asp'\"]",
    mainIframe: "iframe#ifrm_Main",
    claimMemberInput: "input#iMember[name='iMember']",
    claimDosInput: "input#iDOS[name='iDOS']",
    claimTimeFrameSelect: "select#sTimeFrame[name='sTimeFrame']",
    claimSearchSubmit: "input[type='submit'][name='Search'][value='Search']",
    claimResultsTable: "table:has(thead td:has-text('Claim Number'))",
    noClaimsMessage: "span.InformationMsg:has-text('No claims on file.')",
    lineDetailSubmit: "input[type='submit'][name='LineDetail'][value='Show Line Detail'], input[name='LineDetail'][value='Show Line Detail']",
    lineDetailShowSubmit: "input[type='submit'][name='LineDetail'][value='Show Line Detail'], input[name='LineDetail'][value='Show Line Detail']",
    lineDetailHideSubmit: "input[type='submit'][name='LineDetail'][value='Hide Line Detail'], input[name='LineDetail'][value='Hide Line Detail']",
    lineDetailTable: "table:has(td.tdclaim:has-text('SEQNM'))",
  },
  runtime: {
    supportsLocal: true,
    supportsDeployed: true,
    requiresVpn: false,
  },
};
