export const WAYSTAR_CLAIM_STATUS_SELECTORS = {
  navigation: {
    claimsProcessing: [
      "a.selected-tab:has-text('Claims Processing')",
      "text=/Claims Processing/i",
      "a:has-text('Claims Processing')",
      "button:has-text('Claims Processing')",
    ],
    professionalClaims: [
      "a.selected-product:has-text('Professional Claims')",
      "text=/Professional Claims/i",
      "a:has-text('Professional Claims')",
      "button:has-text('Professional Claims')",
    ],
    claims: [
      "a[href*='/Claims/Listing/Index?appid=1']",
      "a:has-text('Claims')",
    ],
    claimSearch: [
      "#headerSearchLink",
      "a[href*='/Claims/ClaimSearch/Index?AppID=1']",
      "text=/Claim Search/i",
      "a:has-text('Claim Search')",
      "button:has-text('Claim Search')",
      "input[value*='Claim Search' i]",
    ],
  },
  search: {
    claimNumber: [
      "#claimNumber",
      "input[data-hinttext*='Claim Number' i]",
      "input[placeholder*='Claim Number' i]",
    ],
    patientName: [
      "#patientName",
      "input[data-hinttext*='John Smith' i]",
      "input[placeholder*='Patient Name' i]",
      "input[aria-label*='Patient Name' i]",
      "label:has-text('Patient Name') + input",
      "label:has-text('Patient') + input",
    ],
    dosFrom: [
      "#dtFrom",
      "input[name='Filters.ServiceStartDate']",
      "input[placeholder*='From DOS' i]",
      "input[placeholder*='DOS From' i]",
      "input[aria-label*='From DOS' i]",
      "label:has-text('From DOS') + input",
    ],
    dosTo: [
      "#dtTo",
      "input[name='Filters.ServiceStopDate']",
      "input[placeholder*='To DOS' i]",
      "input[placeholder*='DOS To' i]",
      "input[aria-label*='To DOS' i]",
      "label:has-text('To DOS') + input",
    ],
    singleDos: [
      "input[placeholder='DOS']",
      "input[placeholder*='Service Date' i]",
      "input[aria-label='DOS']",
      "label:has-text('DOS') + input",
    ],
    payer: [
      "input[placeholder*='Payer' i]",
      "input[aria-label*='Payer' i]",
      "label:has-text('Payer') + input",
    ],
    searchButton: [
      "#searchButton",
      "input[type='button'][value*='Search' i]",
      "button:has-text('Search')",
      "input[type='submit'][value*='Search' i]",
      "button[aria-label*='Search' i]",
    ],
    resetButton: [
      "button:has-text('Reset')",
      "input[type='button'][value*='Reset' i]",
    ],
  },
  results: {
    headers: [
      "table thead th",
      "[role='columnheader']",
      "table tr th",
    ],
    rows: [
      "table.gridView tbody tr.gridViewRow.gridViewExpandableRow",
      ".gridView tr.gridViewRow.gridViewExpandableRow",
      "table tbody tr.gridViewRow.gridViewExpandableRow",
      "table tbody tr",
      ".MuiTableBody-root tr",
      "[role='row']",
    ],
    noResults: [
      "text=/No results/i",
      "text=/No claims found/i",
      "text=/0 results/i",
    ],
    detailLinks: [
      "a:has-text('View')",
      "button:has-text('View')",
      "a:has-text('Details')",
      "button:has-text('Details')",
      "a:has-text('Claim')",
    ],
    historyButtons: [
      "#gridActionMenu .innerGridActionDiv #gridActionHistory",
      "#gridActionMenu .innerGridActionDiv a.gridActionOption:has-text('History')",
      ".innerGridActionDiv #gridActionHistory",
      ".innerGridActionDiv a.gridActionOption:has-text('History')",
      "#gridActionHistory",
      "a.gridActionOption:has-text('History')",
      "a:has-text('History')",
      "button:has-text('History')",
    ],
    eobButtons: [
      "button.mediumDefaultButton.actionBarButton.viewClaimEOBButton.link-open[data-new-window='true'][data-link-url*='ViewEOB.aspx']:has-text('EOB')",
      "button.viewClaimEOBButton.link-open[data-new-window='true'][data-link-url*='ViewEOB.aspx']:has-text('EOB')",
      "button.viewClaimEOBButton:has-text('EOB')",
      "button.mediumDefaultButton.actionBarButton.viewClaimEOBButton:has-text('EOB')",
      "a:has-text('EOB')",
      "button:has-text('EOB')",
    ],
  },
} as const;
