export const blueShieldConfig = {
  id: "blue-shield",
  name: "Blue Shield Claim Status",
  defaultMailbox: "mfa_automation@opusbpo.com",
  selectors: {
    loginRegister: "span.cdl-buttonlogin-text:has-text('Log in/Register'), a:has-text('Log in/Register'), button:has-text('Log in/Register')",
    cookieBanner: "#onetrust-consent-sdk, #onetrust-policy, #onetrust-overlay",
    cookieScrollContainer: "#onetrust-consent-sdk, #onetrust-banner-sdk, #onetrust-policy, #onetrust-overlay",
    cookieAccept: [
      "#onetrust-accept-btn-handler",
      "#onetrust-reject-all-handler",
      "#onetrust-banner-sdk button:has-text('Continue')",
      "#onetrust-banner-sdk button:has-text('CONTINUE')",
      "#onetrust-policy button:has-text('Continue')",
      "#onetrust-policy button:has-text('CONTINUE')",
      "button:has-text('Continue')",
      "#onetrust-consent-sdk button:has-text('Continue')",
      "#onetrust-consent-sdk button:has-text('CONTINUE')",
      "#onetrust-consent-sdk button:has-text('Accept All')",
      "#onetrust-consent-sdk button:has-text('Accept all')",
      "#onetrust-consent-sdk button:has-text('Accept')",
      "#onetrust-consent-sdk a:has-text('Continue')",
      "#onetrust-consent-sdk a:has-text('Accept')",
    ].join(", "),
    cookieClose: "#onetrust-close-btn-container button, button[aria-label*='close' i], .onetrust-close-btn-handler",
    username: "#username",
    password: "#password",
    loginSubmit: "#signOnButton",
    bookmarkProvider: "a[href='https://www.blueshieldca.com/en/provider']",
    otpInput: "#passcode",
    otpSubmit: "button#sign-on:has-text('Confirm')",
    otpContinue: "button#sign-on:has-text('Continue')",
    otpResend: "#sendCode",
    accountMenu: [
      "#member-account-dropdown",
      "#member-account-menu",
      "[title='Account']",
      "div:has-text('Account')",
      "button[aria-label*='account' i]",
      "button[aria-label*='profile' i]",
      "button[aria-label*='user' i]",
      "[role='button'][aria-label*='account' i]",
      "[role='button'][aria-label*='profile' i]",
    ].join(", "),
    logout: [
      "#member-account-logout-link",
      "[title='Log out']",
      "div.dropdown-item:has-text('Log out')",
      "a:has-text('Log out')",
      "button:has-text('Log out')",
      "div:has-text('Log out')",
      "a:has-text('Logout')",
      "button:has-text('Logout')",
      "a:has-text('Sign out')",
      "button:has-text('Sign out')",
    ].join(", "),
    hamburgerMenu: "#cdl-hamburger-menu-btn",
    claimsMenu: [
      "#cdl-nav-item-l1-link-2",
      "a.cdl-nav-item-l1-link:has-text('Claims')",
      "button.cdl-nav-item-l1-link:has-text('Claims')",
      ".cdl-nav-item-l1-link:has(.cdl-nav-item-l1-link-text:has-text('Claims'))",
      ".cdl-nav-item-l1-link-text:has-text('Claims')",
    ].join(", "),
    checkClaimStatus: [
      "a[href*='/providerwebapp/claims/claimStatus']",
      "a[data-href*='/providerwebapp/claims/claimStatus']",
      "a.b2b-l2-menu-list-item-link:has-text('Check claims status')",
      "a:has-text('Check claim status')",
      "a:has-text('Check claims status')",
    ].join(", "),
    memberIdInput: "#memId",
    dosStartInput: "#fromDate",
    dosEndInput: "#toDate",
    dosInput: "#fromDate",
    startOverSearch: "button:has-text('Start over'), a:has-text('Start over'), [role='button']:has-text('Start over')",
    claimEobInput: [
      "input[placeholder*='Claim/EOB' i]",
      "input[aria-label*='Claim/EOB' i]",
      "input[name*='claim' i]",
      "input[id*='claim' i]",
      "input[name*='eob' i]",
      "input[id*='eob' i]",
    ].join(", "),
    checkEftInput: [
      "input[placeholder*='Check/EFT' i]",
      "input[aria-label*='Check/EFT' i]",
      "input[name*='check' i]",
      "input[id*='check' i]",
      "input[name*='eft' i]",
      "input[id*='eft' i]",
    ].join(", "),
    searchSubmit: "#searchBtn",
    resultTable: "table:has(#claimSearchStatus), table",
    resultHeaders: "thead th, tr th",
    resultRows: "table:has(#claimSearchStatus) tbody tr:has(td), table tbody tr:has(td), [data-testid*='claim' i], .claim-row, .result-row",
    claimOpenTarget: "a, button, [role='button']",
    nextResultsPage: "a:has-text('Next'), button:has-text('Next'), [aria-label*='next' i]",
  },
  runtime: {
    supportsLocal: true,
    supportsDeployed: false,
    requiresVpn: true,
  },
};
