import type { WaystarProjectConfig } from "./types";

/** MedRevenue reuses existing payer code; add only verified fallbacks here. */
export const medRevenueWaystarConfig: WaystarProjectConfig = {
  id: "medrevenue",
  requireInputProjectColumn: false,
  allowUnscopedCredentials: true,
  settings: { extractOtherCoverageServiceTypes: true, verifyPayerBeforeSubmit: true },
  inputColumnMappings: {
    dateOfService: ["Date of Service (DOS)", "Plan Date", "Plan Date(s)"],
  },
  payerRoutingRules: [{
    payerId: "cigna-open-access-plus",
    insuranceNameAliases: ["CIGNA"],
    preferInsuranceName: true,
  }, {
    payerId: "aetna",
    insuranceNameAliases: ["Aetna", "Aetna Insurance", "Aetna Health Plans"],
    preferInsuranceName: true,
  }, {
    payerId: "umr",
    insuranceNameAliases: ["UMR", "United Medical Resources"],
    preferInsuranceName: true,
  }, {
    payerId: "scan",
    insuranceNameAliases: ["SCAN", "Scan Health Plan"],
    preferInsuranceName: true,
  }, {
    payerId: "united-healthcare-all-states",
    insuranceNameAliases: ["United Healthcare", "United Health Care", "UnitedHealthcare", "UHC", "Upland Medical Group", "Regal Medical Group"],
    insuranceNameMatch: "contains",
    memberIdPrefixAlternative: "9",
  }, {
    payerId: "blue-shield",
    insuranceNameAliases: ["Blue Shield", "BlueShield", "BlueShiled"],
    insuranceNameMatch: "contains",
    memberIdPrefixAlternative: "X",
  }, {
    payerId: "bcbs-ppo",
    insuranceNameAliases: ["Blue Cross", "Blue Cross California", "Blue Cross of California"],
    preferInsuranceName: true,
    memberIdStartsWithAlphabetic: true,
  }],
  payers: {
    "cigna-open-access-plus": {
      exactCignaPlanDate: true,
      portalPayerName: "Cigna Health Plans (62308)",
      payerSearchText: "Cigna",
      requireExactPayerSuggestionCommit: true,
      restorePatientLookup: true,
      skipProviderHandling: true,
      preserveMemberId: true,
      useDateOfServiceForPlanDates: true,
      fillPlanDatesBeforeServiceType: true,
      planDateToOptional: true,
      fillDateOfBirth: true,
      serviceTypeDirectValue: "30",
      extractFullPayerResponse: true,
    },
    aetna: {
      exactAetnaDates: true,
      portalPayerName: "Aetna (60054)",
      payerSearchText: "Aetna",
      requireExactPayerSuggestionCommit: true,
      restorePatientLookup: true,
      skipProviderHandling: true,
      preserveMemberId: true,
      useDateOfServiceForPlanDates: true,
      fillPlanDatesBeforeServiceType: true,
      planDateToOptional: true,
      fillDateOfBirth: true,
      serviceTypeDirectValue: "30",
      extractFullPayerResponse: true,
    },
    umr: {
      retryPlanDatesWithKeyboard: true,
      exactUmrDates: true,
      portalPayerName: "UMR (39026)",
      payerSearchText: "UMR",
      requireExactPayerSuggestionCommit: true,
      restorePatientLookup: true,
      skipProviderHandling: true,
      preserveMemberId: true,
      useDateOfServiceForPlanDates: true,
      fillPlanDatesBeforeServiceType: true,
      planDateToOptional: true,
      fillDateOfBirth: true,
      serviceTypeDirectValue: "30",
      extractFullPayerResponse: true,
    },
    scan: {
      restorePatientLookup: true,
      skipProviderHandling: true,
      serviceTypeDirectValue: "30",
      fillPlanDatesBeforeServiceType: true,
      portalPayerName: "Scan Health Plan - California(72261)",
      requireExactPayerSuggestionCommit: true,
      preserveMemberId: true,
      useDateOfServiceForPlanDates: true,
      planDateToOptional: true,
      fillDateOfBirth: true,
      extractFullPayerResponse: true,
    },
    "united-healthcare-all-states": {
      restorePatientLookup: true,
      portalPayerName: "UHC (87726)",
      extractUhcOtherCoverage: true,
      memberIdAndDobOnly: true,
      typePlanDate: true,
      requireExactPayerSuggestionCommit: true,
      skipProviderHandling: true,
      useDateOfServiceForPlanDates: true,
      fillPlanDatesBeforeServiceType: true,
      planDateToOptional: true,
      fillDateOfBirth: true,
      preserveMemberId: true,
      serviceTypeDirectValue: "30",
      extractFullPayerResponse: true,
      selectorFallbacks: { planDateFrom: "#txtPlanFrom" },
    },
    "blue-shield": {
      repairPatientValueReset: true,
      payerSearchText: "Blue Shield",
      restorePatientLookup: true,
      portalPayerName: "Blue Shield California(SB542)",
      memberIdAndDobOnly: true,
      requireExactPayerSuggestionCommit: true,
      skipProviderHandling: true,
      useDateOfServiceForPlanDates: true,
      fillPlanDatesBeforeServiceType: true,
      planDateToOptional: true,
      responsePlanDateSectionTitle: "Health Benefit Plan Coverage",
      extractSecondaryCoverage: true,
      fillDateOfBirth: true,
      serviceTypeDirectValue: "30",
      selectorFallbacks: { planDateFrom: "#txtPlanFrom", planDateTo: "#txtPlanTo" },
    },
    medicare: {
      requireSubscriberLookup: true,
      settings: { requireFullPayerName: true },
      requireExactPayerSuggestionCommit: true,
      skipProviderHandling: true,
      useDateOfServiceForPlanDates: true,
      fillDateOfBirth: true,
      serviceTypeDirectValue: "30",
      extractFullPayerResponse: true,
      selectorFallbacks: {
        planDateFrom: "#txtPlanFrom",
        planDateTo: "#txtPlanTo",
        dateOfBirth: "#DOB",
      },
    },
    "bcbs-ppo": {
      restorePatientLookup: true,
      portalPayerName: "Blue Cross California (SB040)",
      fillPlanDatesBeforeServiceType: true,
      requireExactPayerSuggestionCommit: true,
      skipProviderHandling: true,
      useDateOfServiceForPlanDates: true,
      planDateToOptional: true,
      responsePlanDateSectionTitle: "Health Benefit Plan Coverage",
      extractSecondaryCoverage: true,
      fillDateOfBirth: true,
      serviceTypeDirectValue: "30",
      selectorFallbacks: {
        planDateFrom: "#txtPlanFrom",
      },
    },
  },
};
