import type { WaystarProjectConfig } from "./types";

/** MedRevenue reuses existing payer code; add only verified fallbacks here. */
export const medRevenueWaystarConfig: WaystarProjectConfig = {
  id: "medrevenue",
  requireInputProjectColumn: false,
  allowUnscopedCredentials: true,
  inputColumnMappings: {
    dateOfService: ["Date of Service (DOS)", "Plan Date", "Plan Date(s)"],
  },
  payerRoutingRules: [{
    payerId: "united-healthcare-all-states",
    insuranceNameAliases: ["United Healthcare", "United Health Care", "UnitedHealthcare", "UHC", "Upland Medical Group", "Regal Medical Group"],
    insuranceNameMatch: "contains",
    memberIdPrefixAlternative: "9",
  }, {
    payerId: "blue-shield",
    insuranceNameAliases: ["Blue Shield", "BlueShield"],
    insuranceNameMatch: "contains",
    memberIdPrefixAlternative: "X",
  }, {
    payerId: "bcbs-ppo",
    insuranceNameAliases: ["Blue Cross", "Blue Cross California"],
    memberIdStartsWithAlphabetic: true,
  }],
  payers: {
    "united-healthcare-all-states": {
      portalPayerName: "UHC (87726)",
      extractUhcOtherCoverage: true,
      memberIdAndDobOnly: true,
      typePlanDate: true,
      requireExactPayerSuggestionCommit: true,
      skipProviderHandling: true,
      useDateOfServiceForPlanDates: true,
      fillPlanDatesBeforeServiceType: true,
      planDateToOptional: true,
      fillDateOfBirth: true,
      preserveMemberId: true,
      serviceTypeDirectValue: "30",
      extractFullPayerResponse: true,
      selectorFallbacks: { planDateFrom: "#txtPlanFrom" },
    },
    "blue-shield": {
      portalPayerName: "Blue Shield California(SB542)",
      memberIdAndDobOnly: true,
      requireExactPayerSuggestionCommit: true,
      skipProviderHandling: true,
      useDateOfServiceForPlanDates: true,
      fillPlanDatesBeforeServiceType: true,
      planDateToOptional: false,
      responsePlanDateSectionTitle: "Health Benefit Plan Coverage",
      extractSecondaryCoverage: true,
      fillDateOfBirth: true,
      serviceTypeDirectValue: "30",
      selectorFallbacks: { planDateFrom: "#txtPlanFrom", planDateTo: "#txtPlanTo" },
    },
    medicare: {
      skipProviderHandling: true,
      useDateOfServiceForPlanDates: true,
      fillDateOfBirth: true,
      serviceTypeDirectValue: "30",
      extractFullPayerResponse: true,
      selectorFallbacks: {
        planDateFrom: "#txtPlanFrom",
        planDateTo: "#txtPlanTo",
        dateOfBirth: "#DOB",
      },
    },
    "bcbs-ppo": {
      portalPayerName: "Blue Cross California (SB040)",
      fillPlanDatesBeforeServiceType: true,
      requireExactPayerSuggestionCommit: true,
      skipProviderHandling: true,
      useDateOfServiceForPlanDates: true,
      planDateToOptional: true,
      responsePlanDateSectionTitle: "Health Benefit Plan Coverage",
      extractSecondaryCoverage: true,
      fillDateOfBirth: true,
      serviceTypeDirectValue: "30",
      selectorFallbacks: {
        planDateFrom: "#txtPlanFrom",
      },
    },
  },
};
