export const kaiserConfig = {
  id: "kaiser",
  name: "KAISER Claim Status",
  defaultLoginUrl: "https://epiclink-cs.kp.org/cs/common/epic_main.asp",
  selectors: {
    username: "#username, input[name='pf.username']",
    password: "#password, input[name='pf.pass']",
    submit: "#submitBtnID, input[type='submit'][value='Sign on']",
    loginMessage: ".loginMsgWrap",
    loginMessageAccept: [
      "#toolbar1button1[title='Acknowledge and continue']",
      "td.toolbarBottomBtn[title='Acknowledge and continue']",
      "td.toolbarBottomBtn:has-text('Accept')",
      "a.toolbarBottomText:has-text('Accept')",
    ].join(", "),
    fontDialogOk: ".ui-dialog-buttonpane button:has-text('OK'), button:has-text('OK')",
    claimSearchCard: [
      "a.quick-button[onclick*='claims_claimprovreview']",
      "a.quick-button[title='Search claims based on various criteria']",
      "a.quick-button:has-text('Claim Search')",
    ].join(", "),
    claimsTopNav: "a:has-text('Claims'), [title*='Claims']",
    claimSearchTab: "a:has-text('Claim Search'), .Tab:has-text('Claim Search')",
    advancedSearch: "a.CollapseDIV:has-text('Advanced Search'), a:has-text('Advanced Search')",
    megaSearch: [
      "#txtMegaSearch",
      "input[name='txtMegaSearch']",
      "input[placeholder*='Search for vendor' i]",
      "input[placeholder*='member ID' i]",
      "input[placeholder*='claim ID' i]",
    ].join(", "),
    memberId: "#txtMRN, input[name='txtMRN']",
    fromDate: [
      "#txtFromDate",
      "input[name='txtFromDate']",
      "input[id*='from' i][id*='date' i]",
      "input[name*='from' i][name*='date' i]",
      "input[aria-label*='From date' i]",
      "input[title*='From date' i]",
      "input:right-of(:text('From date'))",
    ].join(", "),
    toDate: [
      "#txtToDate",
      "input[name='txtToDate']",
      "input[id*='to' i][id*='date' i]",
      "input[name*='to' i][name*='date' i]",
      "input[aria-label*='To date' i]",
      "input[title*='To date' i]",
      "input:right-of(:text('To date'))",
    ].join(", "),
    searchButtons: [
      "#SearchButton",
      "#cmdSearch",
      "input[type='button'][value='Search']",
      "input[type='submit'][value='Search']",
      "button:has-text('Search')",
      "a:has-text('Search')",
    ].join(", "),
  },
  timing: {
    dropdownSettleMs: 900,
    postSelectionMs: 1000,
    preSearchMs: 800,
    postResultMs: 1800,
    betweenRowsMs: 1500,
    retryBackoffMs: 1200,
    stablePollMs: 150,
    claimDetailExtractionTimeoutMs: 15000,
  },
  runtime: {
    supportsLocal: true,
    supportsDeployed: false,
    requiresVpn: true,
  },
};
