export const kaiserConfig = {
  id: "kaiser",
  name: "KAISER Claim Status",
  defaultLoginUrl: "https://epiclink-cs.kp.org/cs/common/epic_main.asp",
  selectors: {
    username: "#username, input[name='pf.username']",
    password: "#password, input[name='pf.pass']",
    submit: "#submitBtnID, input[type='submit'][value='Sign on']",
    fontDialogOk: ".ui-dialog-buttonpane button:has-text('OK'), button:has-text('OK')",
    claimSearchCard: [
      "a.quick-button[onclick*='claims_claimprovreview']",
      "a.quick-button[title='Search claims based on various criteria']",
      "a.quick-button:has-text('Claim Search')",
    ].join(", "),
    claimsTopNav: "a:has-text('Claims'), [title*='Claims']",
    claimSearchTab: "a:has-text('Claim Search'), .Tab:has-text('Claim Search')",
    advancedSearch: "a.CollapseDIV:has-text('Advanced Search'), a:has-text('Advanced Search')",
    megaSearch: "#txtMegaSearch, input[name='txtMegaSearch']",
    memberId: "#txtMRN, input[name='txtMRN']",
    fromDate: "#txtFromDate, input[name='txtFromDate']",
    toDate: "#txtToDate, input[name='txtToDate']",
    searchButtons: [
      "#SearchButton",
      "#cmdSearch",
      "input[type='button'][value='Search']",
      "input[type='submit'][value='Search']",
      "button:has-text('Search')",
      "a:has-text('Search')",
    ].join(", "),
  },
  timing: {
    dropdownSettleMs: 900,
    postSelectionMs: 1000,
    preSearchMs: 800,
    postResultMs: 1800,
    betweenRowsMs: 1500,
    retryBackoffMs: 1200,
    stablePollMs: 150,
  },
  runtime: {
    supportsLocal: true,
    supportsDeployed: false,
    requiresVpn: true,
  },
};
