export const myFamilyConfig = {
  id: "my-family",
  name: "My family Claim Status",
  defaultLoginUrl: "https://ezcap.myfamilymg.com/EZ-NET60/Login.aspx",
  claimSearchUrl: "https://ezcap.myfamilymg.com/EZ-NET60/Webportal/EZNET/ClaimSearch.aspx",
  selectors: {
    loginLink: "#tblLogin a[onclick*='showLogin'], #tblLogin a:has-text('Login')",
    username: "#MainContent_ctl00_txtUserName, input[name='ctl00$MainContent$ctl00$txtUserName']",
    password: "#MainContent_ctl00_txtPassword, input[name='ctl00$MainContent$ctl00$txtPassword']",
    submit: ".form-login #MainContent_ctl00_btnLogin, .form-login input[name='ctl00$MainContent$ctl00$btnLogin'][value='Login']",
    mainMenu: "#hyperMainMenu, input[value='Main Menu']",
    claimsMenu: "text=Claims",
    claimSearchLink: "a:has-text('Search'), text=Search",
    memberId: "#MainContent_txtMemberID",
    patientFirstName: "#MainContent_txtPatientFirstName",
    patientLastName: "#MainContent_txtPatientLastName",
    serviceDateFrom: "#MainContent_wdcServiceDateFrom input[type='text']",
    serviceDateTo: "#MainContent_wdcServiceDateTo input[type='text']",
    searchButton: "#MainContent_btnSearch",
    clearButton: "#MainContent_btnClear",
    resultGrid: "#MainContent_UWGClaimSearch",
    resultRows: "#MainContent_UWGClaimSearch tbody[mkr='rows'] tr, #MainContent_UWGClaimSearch tr[role='row']",
    noData: "#MainContent_lblNoData",
    detailsMarker: "text=Claim / Encounter Details",
    servicesGrid: "#MainContent_UWGServicesRequested",
  },
  timing: {
    postLoginMs: 1800,
    postNavigationMs: 1200,
    postSearchMs: 1800,
    betweenRowsMs: 1200,
    detailLoadMs: 1500,
  },
  runtime: {
    supportsLocal: true,
    supportsDeployed: false,
    requiresVpn: true,
  },
};
