export const physiciansConfig = {
  id: "physicians",
  name: "Physicians Claim Status",
  defaultLoginUrl: "https://phn.quickcap.net/PHN/general/index.php",
  claimSearchUrl:
    "https://phn.quickcap.net/PHN/general/index.php?file=med_dashboard_frame&link_module=25&link_id=144&isAjax=no",
  selectors: {
    username: "#TaRtxt_username",
    password: "#TaRpas_password",
    submit: "input[type='submit'][value='Login'], input.orang-btn[value='Login']",
    announcementClose: "#block a.lnk-Close, #block a:has-text('Close')",
    announcementBlock: "#block",
    claimsSection: "#section_title_80, h3:has-text('Claims')",
    claimSearchLink: "a:has-text('Claims Search/Status')",
    claimNoFrom: "#txtClaimNoFrom",
    claimNoTo: "#txtClaimNoTo",
    authNo: "#txtAuthNo",
    providerClaimNo: "#txtProvClaimNo",
    memberId: "#txtMemberID",
    serviceDateFrom: "#txtSvcDateFrom_txtDate",
    serviceDateTo: "#txtSvcDateTo_txtDate",
    searchButton: "#btnSearch",
    clearButton: "#btnClear",
    resultGrid: "#grdClaimsView",
    resultRows: "#grdClaimsView > tbody > tr",
    noData: "text=/No Claims Found|No Records Found|No Member Found|Member Not Found/i",
  },
  timing: {
    postLoginMs: 2500,
    postNavigationMs: 1500,
    postSearchMs: 1500,
    betweenRowsMs: 1200,
  },
  runtime: {
    supportsLocal: true,
    supportsDeployed: false,
    requiresVpn: true,
  },
};